# Generated by Django 5.1.2 on 2024-10-15 03:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_expense_date_remove_revenue_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
